import { test, expect } from '@playwright/test'

test('forecast horizons, site switching, downloads, and all workspace views', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your energy, in perspective.' })).toBeVisible()
  await page.screenshot({ path: 'test-results/overview-desktop.png', fullPage: true })
  await page.getByRole('navigation').getByRole('button', { name: 'Generation forecast' }).click()
  await page.getByRole('button', { name: '72h', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(72)
  await page.getByLabel('Select energy site').selectOption('tirunelveli')
  await expect(page.locator('tbody tr').first().locator('td').nth(1)).toHaveText('0')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export forecast' }).click()
  expect((await download).suggestedFilename()).toBe('tirunelveli-72h-forecast.csv')
  for (const name of ['AI insights', 'Risk & decisions', 'Digital twin', 'Impact & reports']) {
    await page.getByRole('navigation').getByRole('button', { name }).click()
    await expect(page.locator('main h1')).toBeVisible()
    await expect(page.locator('main')).not.toContainText('NaN')
  }
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByLabel('Display name').fill('Priya Shah')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await page.reload()
  await expect(page.getByLabel('Display name')).toHaveValue('Priya Shah')
  expect(errors).toEqual([])
})

test('simulator calculates changes, saves comparisons, persists and deletes them', async ({ page }) => {
  await page.goto('/#What-If%20simulator')
  const baseline = await page.locator('.scenario-results strong').first().innerText()
  await page.getByLabel('Quick scenario').selectOption('cloudy')
  await expect(page.getByText('Changes not simulated')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save scenario to reports' })).toBeDisabled()
  await page.getByRole('button', { name: 'Run simulation', exact: true }).click()
  await expect(page.locator('.scenario-results strong').first()).not.toHaveText(baseline)
  await page.getByRole('button', { name: 'Save scenario to reports' }).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Impact & reports' }).click()
  await expect(page.getByText('85% cloud · 0% demand · 72% battery')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Scenario 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete scenario 1' }).click()
  await expect(page.getByRole('button', { name: 'Create a scenario' })).toBeVisible()
})

test('action plan, copilot, notifications, digital twin and modal keyboard behavior', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Review action', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Save to local plan' }).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Risk & decisions' }).click()
  await expect(page.getByText('Saved to local plan')).toBeVisible()
  await page.getByRole('button', { name: 'Ask Copilot', exact: true }).click()
  await page.getByRole('button', { name: 'What is driving my risk?' }).click()
  await expect(page.locator('.chat-answer')).toContainText('demo risk score')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Notifications', exact: true }).click()
  await page.getByRole('button', { name: 'Mark read' }).click()
  await expect(page.locator('.notification-button i')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button', { name: 'Digital twin' }).click()
  await page.getByLabel('Explore a forecast hour').fill('14')
  await expect(page.locator('.twin-timeline')).toContainText('20:00 IST')
})

test('mobile navigation and every view fit narrow screens', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.screenshot({ path: 'test-results/overview-mobile.png', fullPage: true })
  for (const name of ['Generation forecast', 'AI insights', 'Risk & decisions', 'What-If simulator', 'Digital twin', 'Impact & reports']) {
    await page.getByRole('button', { name: 'Open navigation' }).click()
    await page.getByRole('navigation').getByRole('button', { name }).click()
    await expect(page.locator('main h1')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.getByRole('button', { name: 'Ask Copilot', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
